version: '3.4'

services:
  lifoid:
    image: lifoid
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m lifoid mqtt_bot --host mosquitto"
    ports:
      - 5678:5678

