version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  lifoid:
    image: lifoid
    command: lifoid mqtt_bot --host mosquitto
    depends_on:
      - mosquitto
    volumes:
      - ./bot:/app/bot
    environment:
      LIFOID_SETTINGS_MODULE: bot.settings
      LOGGING_SERVICE: lifoid
      LOGGING_DEBUG: "no"
      LOGGING_HANDLERS: console,logfile,rotatedlogfile,debug
      LOGGING_FILE: lifoid.log
      LOGGING_ROTATED_FILE_INTERVAL: H